"""
Instagram Authentication Helper

To get a real Instagram access token:

1. Go to Facebook Developers: https://developers.facebook.com/
2. Create a new app
3. Add Instagram Basic Display product
4. Configure OAuth redirect URIs
5. Get your App ID and App Secret

For testing, you can use Instagram's test users or your own account.
"""

import requests
from urllib.parse import urlencode

class InstagramAuth:
    def __init__(self, app_id, app_secret, redirect_uri):
        self.app_id = app_id
        self.app_secret = app_secret
        self.redirect_uri = redirect_uri
        self.base_url = "https://api.instagram.com"
        
    def get_authorization_url(self):
        """Generate Instagram authorization URL"""
        params = {
            'client_id': self.app_id,
            'redirect_uri': self.redirect_uri,
            'scope': 'user_profile,user_media',
            'response_type': 'code'
        }
        
        auth_url = f"{self.base_url}/oauth/authorize?" + urlencode(params)
        return auth_url
    
    def exchange_code_for_token(self, code):
        """Exchange authorization code for access token"""
        url = f"{self.base_url}/oauth/access_token"
        
        data = {
            'client_id': self.app_id,
            'client_secret': self.app_secret,
            'grant_type': 'authorization_code',
            'redirect_uri': self.redirect_uri,
            'code': code
        }
        
        response = requests.post(url, data=data)
        
        if response.status_code == 200:
            return response.json()
        else:
            return None
    
    def get_long_lived_token(self, short_lived_token):
        """Convert short-lived token to long-lived token (60 days)"""
        url = "https://graph.instagram.com/access_token"
        
        params = {
            'grant_type': 'ig_exchange_token',
            'client_secret': self.app_secret,
            'access_token': short_lived_token
        }
        
        response = requests.get(url, params=params)
        
        if response.status_code == 200:
            return response.json()
        else:
            return None

# Example usage:
"""
# 1. Initialize auth helper
auth = InstagramAuth(
    app_id="YOUR_APP_ID",
    app_secret="YOUR_APP_SECRET", 
    redirect_uri="http://localhost:8000/auth/instagram/callback"
)

# 2. Get authorization URL (user visits this)
auth_url = auth.get_authorization_url()
print(f"Visit: {auth_url}")

# 3. After user authorizes, Instagram redirects with code
# Extract code from callback URL and exchange for token
token_data = auth.exchange_code_for_token("AUTHORIZATION_CODE")

# 4. Get long-lived token
long_token = auth.get_long_lived_token(token_data['access_token'])
"""

# For demo purposes, here's how to test with your own Instagram account:
DEMO_INSTRUCTIONS = """
🔧 How to get Instagram Access Token for Testing:

1. **Create Facebook App:**
   - Go to https://developers.facebook.com/
   - Create new app → "Consumer" type
   - Add "Instagram Basic Display" product

2. **Configure Instagram Basic Display:**
   - Add test user (your Instagram account)
   - Set redirect URI: http://localhost:8000/auth/callback
   - Copy App ID and App Secret

3. **Get Access Token:**
   - Visit authorization URL (generated by code above)
   - Login with your Instagram account
   - Copy the access token from callback

4. **Use in Fraud Detector:**
   - Paste token in the frontend
   - Set use_mock_data = false
   - Analyze your real Instagram data!

⚠️ Note: Instagram Basic Display API has limitations:
- Only works with test users initially
- Requires app review for production
- Rate limited (200 requests/hour)

For production, consider using:
- Instagram Graph API (for business accounts)
- Third-party services like RapidAPI
- Web scraping (with proper rate limiting)
"""

print(DEMO_INSTRUCTIONS)